#############################################################################
# Makefile for building: Game2.app/Contents/MacOS/Game2
# Generated by qmake (3.1) (Qt 6.5.1)
# Project:  ../Game2/Game2.pro
# Template: app
# Command: /Users/v/QT/6.5.1/macos/bin/qmake -o Makefile ../Game2/Game2.pro -spec macx-clang CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I../Game2 -I. -I../../../QT/6.5.1/macos/lib/QtWidgets.framework/Headers -I../../../QT/6.5.1/macos/lib/QtGui.framework/Headers -I../../../QT/6.5.1/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../QT/6.5.1/macos/mkspecs/macx-clang -F/Users/v/QT/6.5.1/macos/lib
QMAKE         = /Users/v/QT/6.5.1/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/v/QT/6.5.1/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/v/QT/6.5.1/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Game21.0.0
DISTDIR = /Users/v/Desktop/QtProjekte/build-Game2-Qt_6_5_1_for_macOS-Release/.tmp/Game21.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/v/QT/6.5.1/macos/lib
LIBS          = $(SUBLIBS) -F/Users/v/QT/6.5.1/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Game2/main.cpp \
		../Game2/mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = ../../../QT/6.5.1/macos/mkspecs/features/spec_pre.prf \
		../../../QT/6.5.1/macos/mkspecs/features/device_config.prf \
		../../../QT/6.5.1/macos/mkspecs/common/unix.conf \
		../../../QT/6.5.1/macos/mkspecs/common/mac.conf \
		../../../QT/6.5.1/macos/mkspecs/common/macx.conf \
		../../../QT/6.5.1/macos/mkspecs/common/sanitize.conf \
		../../../QT/6.5.1/macos/mkspecs/common/gcc-base.conf \
		../../../QT/6.5.1/macos/mkspecs/common/gcc-base-mac.conf \
		../../../QT/6.5.1/macos/mkspecs/common/clang.conf \
		../../../QT/6.5.1/macos/mkspecs/common/clang-mac.conf \
		../../../QT/6.5.1/macos/mkspecs/qconfig.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_core.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_help.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_network.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../../QT/6.5.1/macos/mkspecs/features/qt_functions.prf \
		../../../QT/6.5.1/macos/mkspecs/features/qt_config.prf \
		../../../QT/6.5.1/macos/mkspecs/macx-clang/qmake.conf \
		../../../QT/6.5.1/macos/mkspecs/features/spec_post.prf \
		../../../QT/6.5.1/macos/mkspecs/features/exclusive_builds.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/sdk.prf \
		../../../QT/6.5.1/macos/mkspecs/features/toolchain.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/toolchain.prf \
		../../../QT/6.5.1/macos/mkspecs/features/default_pre.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/default_pre.prf \
		../../../QT/6.5.1/macos/mkspecs/features/resolve_config.prf \
		../../../QT/6.5.1/macos/mkspecs/features/default_post.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/default_post.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/objective_c.prf \
		../../../QT/6.5.1/macos/mkspecs/features/qtquickcompiler.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/mac.prf \
		../../../QT/6.5.1/macos/mkspecs/features/warn_on.prf \
		../../../QT/6.5.1/macos/mkspecs/features/permissions.prf \
		../../../QT/6.5.1/macos/mkspecs/features/qt.prf \
		../../../QT/6.5.1/macos/mkspecs/features/resources_functions.prf \
		../../../QT/6.5.1/macos/mkspecs/features/resources.prf \
		../../../QT/6.5.1/macos/mkspecs/features/moc.prf \
		../../../QT/6.5.1/macos/mkspecs/features/unix/opengl.prf \
		../../../QT/6.5.1/macos/mkspecs/features/uic.prf \
		../../../QT/6.5.1/macos/mkspecs/features/unix/thread.prf \
		../../../QT/6.5.1/macos/mkspecs/features/qmake_use.prf \
		../../../QT/6.5.1/macos/mkspecs/features/file_copies.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/rez.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../QT/6.5.1/macos/mkspecs/features/testcase_targets.prf \
		../../../QT/6.5.1/macos/mkspecs/features/exceptions.prf \
		../../../QT/6.5.1/macos/mkspecs/features/yacc.prf \
		../../../QT/6.5.1/macos/mkspecs/features/lex.prf \
		../Game2/Game2.pro ../Game2/mainwindow.h ../Game2/main.cpp \
		../Game2/mainwindow.cpp
QMAKE_TARGET  = Game2
DESTDIR       = 
TARGET        = Game2.app/Contents/MacOS/Game2

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 13.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = 
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/v/Desktop/QtProjekte/Game2/Game2.pro


include /Users/v/QT/6.5.1/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Game2.app/Contents/MacOS/Game2: ui_mainwindow.h $(OBJECTS)  
	@test -d Game2.app/Contents/MacOS/ || mkdir -p Game2.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../Game2/Game2.pro ../../../QT/6.5.1/macos/mkspecs/macx-clang/qmake.conf ../../../QT/6.5.1/macos/mkspecs/features/spec_pre.prf \
		../../../QT/6.5.1/macos/mkspecs/features/device_config.prf \
		../../../QT/6.5.1/macos/mkspecs/common/unix.conf \
		../../../QT/6.5.1/macos/mkspecs/common/mac.conf \
		../../../QT/6.5.1/macos/mkspecs/common/macx.conf \
		../../../QT/6.5.1/macos/mkspecs/common/sanitize.conf \
		../../../QT/6.5.1/macos/mkspecs/common/gcc-base.conf \
		../../../QT/6.5.1/macos/mkspecs/common/gcc-base-mac.conf \
		../../../QT/6.5.1/macos/mkspecs/common/clang.conf \
		../../../QT/6.5.1/macos/mkspecs/common/clang-mac.conf \
		../../../QT/6.5.1/macos/mkspecs/qconfig.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_core.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_help.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_network.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../../QT/6.5.1/macos/mkspecs/features/qt_functions.prf \
		../../../QT/6.5.1/macos/mkspecs/features/qt_config.prf \
		../../../QT/6.5.1/macos/mkspecs/macx-clang/qmake.conf \
		../../../QT/6.5.1/macos/mkspecs/features/spec_post.prf \
		../../../QT/6.5.1/macos/mkspecs/features/exclusive_builds.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/sdk.prf \
		../../../QT/6.5.1/macos/mkspecs/features/toolchain.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/toolchain.prf \
		../../../QT/6.5.1/macos/mkspecs/features/default_pre.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/default_pre.prf \
		../../../QT/6.5.1/macos/mkspecs/features/resolve_config.prf \
		../../../QT/6.5.1/macos/mkspecs/features/default_post.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/default_post.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/objective_c.prf \
		../../../QT/6.5.1/macos/mkspecs/features/qtquickcompiler.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/mac.prf \
		../../../QT/6.5.1/macos/mkspecs/features/warn_on.prf \
		../../../QT/6.5.1/macos/mkspecs/features/permissions.prf \
		../../../QT/6.5.1/macos/mkspecs/features/qt.prf \
		../../../QT/6.5.1/macos/mkspecs/features/resources_functions.prf \
		../../../QT/6.5.1/macos/mkspecs/features/resources.prf \
		../../../QT/6.5.1/macos/mkspecs/features/moc.prf \
		../../../QT/6.5.1/macos/mkspecs/features/unix/opengl.prf \
		../../../QT/6.5.1/macos/mkspecs/features/uic.prf \
		../../../QT/6.5.1/macos/mkspecs/features/unix/thread.prf \
		../../../QT/6.5.1/macos/mkspecs/features/qmake_use.prf \
		../../../QT/6.5.1/macos/mkspecs/features/file_copies.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/rez.prf \
		../../../QT/6.5.1/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../QT/6.5.1/macos/mkspecs/features/testcase_targets.prf \
		../../../QT/6.5.1/macos/mkspecs/features/exceptions.prf \
		../../../QT/6.5.1/macos/mkspecs/features/yacc.prf \
		../../../QT/6.5.1/macos/mkspecs/features/lex.prf \
		../Game2/Game2.pro \
		../../../QT/6.5.1/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../QT/6.5.1/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../../../QT/6.5.1/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile ../Game2/Game2.pro -spec macx-clang CONFIG+=qtquickcompiler
../../../QT/6.5.1/macos/mkspecs/features/spec_pre.prf:
../../../QT/6.5.1/macos/mkspecs/features/device_config.prf:
../../../QT/6.5.1/macos/mkspecs/common/unix.conf:
../../../QT/6.5.1/macos/mkspecs/common/mac.conf:
../../../QT/6.5.1/macos/mkspecs/common/macx.conf:
../../../QT/6.5.1/macos/mkspecs/common/sanitize.conf:
../../../QT/6.5.1/macos/mkspecs/common/gcc-base.conf:
../../../QT/6.5.1/macos/mkspecs/common/gcc-base-mac.conf:
../../../QT/6.5.1/macos/mkspecs/common/clang.conf:
../../../QT/6.5.1/macos/mkspecs/common/clang-mac.conf:
../../../QT/6.5.1/macos/mkspecs/qconfig.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_ext_freetype.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_ext_libpng.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_concurrent.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_core.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_core_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_dbus.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_designer.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_designer_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_gui.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_gui_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_help.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_help_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labssettings.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_linguist.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_network.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_network_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_opengl.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_png_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_printsupport.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qml.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qml_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmltest.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quick.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quick_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_sql.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_sql_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_svg.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_svg_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_testlib.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_tools_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_uitools.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_widgets.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_xml.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_lib_xml_private.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../../../QT/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../../../QT/6.5.1/macos/mkspecs/features/qt_functions.prf:
../../../QT/6.5.1/macos/mkspecs/features/qt_config.prf:
../../../QT/6.5.1/macos/mkspecs/macx-clang/qmake.conf:
../../../QT/6.5.1/macos/mkspecs/features/spec_post.prf:
../../../QT/6.5.1/macos/mkspecs/features/exclusive_builds.prf:
../../../QT/6.5.1/macos/mkspecs/features/mac/sdk.prf:
../../../QT/6.5.1/macos/mkspecs/features/toolchain.prf:
../../../QT/6.5.1/macos/mkspecs/features/mac/toolchain.prf:
../../../QT/6.5.1/macos/mkspecs/features/default_pre.prf:
../../../QT/6.5.1/macos/mkspecs/features/mac/default_pre.prf:
../../../QT/6.5.1/macos/mkspecs/features/resolve_config.prf:
../../../QT/6.5.1/macos/mkspecs/features/default_post.prf:
../../../QT/6.5.1/macos/mkspecs/features/mac/default_post.prf:
../../../QT/6.5.1/macos/mkspecs/features/mac/objective_c.prf:
../../../QT/6.5.1/macos/mkspecs/features/qtquickcompiler.prf:
../../../QT/6.5.1/macos/mkspecs/features/mac/mac.prf:
../../../QT/6.5.1/macos/mkspecs/features/warn_on.prf:
../../../QT/6.5.1/macos/mkspecs/features/permissions.prf:
../../../QT/6.5.1/macos/mkspecs/features/qt.prf:
../../../QT/6.5.1/macos/mkspecs/features/resources_functions.prf:
../../../QT/6.5.1/macos/mkspecs/features/resources.prf:
../../../QT/6.5.1/macos/mkspecs/features/moc.prf:
../../../QT/6.5.1/macos/mkspecs/features/unix/opengl.prf:
../../../QT/6.5.1/macos/mkspecs/features/uic.prf:
../../../QT/6.5.1/macos/mkspecs/features/unix/thread.prf:
../../../QT/6.5.1/macos/mkspecs/features/qmake_use.prf:
../../../QT/6.5.1/macos/mkspecs/features/file_copies.prf:
../../../QT/6.5.1/macos/mkspecs/features/mac/rez.prf:
../../../QT/6.5.1/macos/mkspecs/features/mac/asset_catalogs.prf:
../../../QT/6.5.1/macos/mkspecs/features/testcase_targets.prf:
../../../QT/6.5.1/macos/mkspecs/features/exceptions.prf:
../../../QT/6.5.1/macos/mkspecs/features/yacc.prf:
../../../QT/6.5.1/macos/mkspecs/features/lex.prf:
../Game2/Game2.pro:
../../../QT/6.5.1/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../QT/6.5.1/macos/lib/QtGui.framework/Resources/QtGui.prl:
../../../QT/6.5.1/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../Game2/Game2.pro -spec macx-clang CONFIG+=qtquickcompiler

qmake_all: FORCE

Game2.app/Contents/PkgInfo: 
	@test -d Game2.app/Contents || mkdir -p Game2.app/Contents
	@$(DEL_FILE) Game2.app/Contents/PkgInfo
	@echo "APPL????" > Game2.app/Contents/PkgInfo
Game2.app/Contents/Info.plist: 
	@test -d Game2.app/Contents || mkdir -p Game2.app/Contents
	@$(DEL_FILE) Game2.app/Contents/Info.plist
	@plutil -convert xml1 -o - ../../../QT/6.5.1/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,test.Game2,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},test.Game2,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Game2,g" -e "s,@LIBRARY@,Game2,g" -e "s,\$${EXECUTABLE_NAME},Game2,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >Game2.app/Contents/Info.plist

all: Makefile \
		Game2.app/Contents/PkgInfo \
		Game2.app/Contents/Info.plist Game2.app/Contents/MacOS/Game2

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../Game2/mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents ../Game2/main.cpp ../Game2/mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../Game2/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Game2.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=qtquickcompiler

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../Game2/mainwindow.h \
		../../../QT/6.5.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../QT/6.5.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../QT/6.5.1/macos/lib/QtGui.framework/Headers/QIntValidator \
		../../../QT/6.5.1/macos/lib/QtGui.framework/Headers/qvalidator.h \
		../../../QT/6.5.1/macos/libexec/moc
	/Users/v/QT/6.5.1/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/v/QT/6.5.1/macos/mkspecs/macx-clang -I/Users/v/Desktop/QtProjekte/Game2 -I/Users/v/QT/6.5.1/macos/lib/QtWidgets.framework/Headers -I/Users/v/QT/6.5.1/macos/lib/QtGui.framework/Headers -I/Users/v/QT/6.5.1/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/v/QT/6.5.1/macos/lib ../Game2/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../Game2/mainwindow.ui \
		../../../QT/6.5.1/macos/libexec/uic
	/Users/v/QT/6.5.1/macos/libexec/uic ../Game2/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../Game2/main.cpp ../Game2/mainwindow.h \
		../../../QT/6.5.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../QT/6.5.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../QT/6.5.1/macos/lib/QtGui.framework/Headers/QIntValidator \
		../../../QT/6.5.1/macos/lib/QtGui.framework/Headers/qvalidator.h \
		../../../QT/6.5.1/macos/lib/QtWidgets.framework/Headers/QApplication \
		../../../QT/6.5.1/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Game2/main.cpp

mainwindow.o: ../Game2/mainwindow.cpp ../Game2/mainwindow.h \
		../../../QT/6.5.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../QT/6.5.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../QT/6.5.1/macos/lib/QtGui.framework/Headers/QIntValidator \
		../../../QT/6.5.1/macos/lib/QtGui.framework/Headers/qvalidator.h \
		ui_mainwindow.h \
		../../../QT/6.5.1/macos/lib/QtCore.framework/Headers/QDebug \
		../../../QT/6.5.1/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../Game2/mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Game2/bin || mkdir -p $(INSTALL_ROOT)/opt/Game2/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Game2/bin/Game2.app
	
	$(QINSTALL) Game2.app $(INSTALL_ROOT)/opt/Game2/bin/Game2.app
	-$(STRIP) $(INSTALL_ROOT)/opt/Game2/bin/Game2.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Game2/bin/Game2.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Game2/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

